channel.channelExitNet=http://bbs.g.qq.com/forum.php?mod=forumdisplay&fid=153
channel.gw=http://king9.cn
channel.id=gbsglm
channel.motherId=gamebox
channel.num=0000480502
channel.passport=https://sglmpass.3gking.net:12443/
channel.specilAttr=
channel.suffix=gbsglm
macros.os=android
macros.resNum=7
macros.resType=HighFull
macros.typeNum=054
packetGame.shareLink=
packetName.j2me=三国·帝王联盟
version.assets=137001
version.fullnum=v1.66.0606
version.num=1660606
version.res=20260526
