#!/bin/zsh
set -euo pipefail

# One-click LAN mode for the Android control surface.  The token is persisted
# only in a private file outside the web root; it is never exposed as a static
# report file by SimpleHTTPRequestHandler.
DIR="$(cd "$(dirname "$0")" && pwd)"
USER_HOME="${HOME:-/Users/${USER:-$(id -un)}}"
MOBILE_CONFIG_DIR="${DWPM_MOBILE_API_CONFIG_DIR:-$USER_HOME/Library/Application Support/DWPMDesktop}"
MOBILE_CONFIG_FILE="$MOBILE_CONFIG_DIR/mobile_api.env"

# Keep the LAN credential outside the web root.  This lets a normal restart
# preserve the phone pairing without making the token downloadable as a
# static report file.  Explicit bind/token environment values always win.
if [[ -z "${DWPM_MOBILE_API_TOKEN:-}" && -z "${DWPM_DESKTOP_BIND_HOST:-}" && -f "$MOBILE_CONFIG_FILE" ]]; then
  source "$MOBILE_CONFIG_FILE"
fi
BIND_HOST="${DWPM_DESKTOP_BIND_HOST:-0.0.0.0}"

if [[ -n "${DWPM_MOBILE_API_TOKEN:-}" ]]; then
  MOBILE_TOKEN="$DWPM_MOBILE_API_TOKEN"
else
  print -n "请输入 Mobile API Token（直接回车使用已保存/自动生成）："
  read -r -s MOBILE_TOKEN
  print
  if [[ -z "$MOBILE_TOKEN" ]]; then
    MOBILE_TOKEN="$(/usr/bin/python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
  fi
fi

if [[ -z "$MOBILE_TOKEN" ]]; then
  print -u2 "Mobile API Token 不能为空，已取消。"
  exit 1
fi

export DWPM_DESKTOP_BIND_HOST="$BIND_HOST"
export DWPM_MOBILE_API_TOKEN="$MOBILE_TOKEN"
# A process-local secret is sufficient for a single run.  Set
# DWPM_MOBILE_API_SECRET yourself when opaque account references must remain
# stable across desktop restarts.
if [[ -z "${DWPM_MOBILE_API_SECRET:-}" ]]; then
  export DWPM_MOBILE_API_SECRET="$(/usr/bin/python3 -c 'import secrets; print(secrets.token_urlsafe(32))')"
fi

# Persist only the pairing settings, never account passwords or game session
# data.  The directory/file permissions are intentionally private to this
# macOS user; the file lives outside the directory served by server.py.
umask 077
mkdir -p "$MOBILE_CONFIG_DIR"
/usr/bin/python3 - "$MOBILE_CONFIG_FILE" "$BIND_HOST" "$MOBILE_TOKEN" "$DWPM_MOBILE_API_SECRET" <<'PY'
from pathlib import Path
import os
import shlex
import sys

path = Path(sys.argv[1])
bind_host, token, secret = (shlex.quote(value) for value in sys.argv[2:5])
path.write_text(
    "# Generated by 开启电脑端手机API.command\n"
    f"export DWPM_DESKTOP_BIND_HOST={bind_host}\n"
    f"export DWPM_MOBILE_API_TOKEN={token}\n"
    f"export DWPM_MOBILE_API_SECRET={secret}\n",
    encoding="utf-8",
)
os.chmod(path, 0o600)
PY

LAN_IP="$(/sbin/ifconfig 2>/dev/null | /usr/bin/awk '/inet / && $2 !~ /^127\\./ {print $2; exit}')"
LAN_IP="${LAN_IP:-电脑局域网IP}"
print "电脑端手机 API 即将启动："
print "  绑定地址：$BIND_HOST"
print "  手机入口：http://$LAN_IP:17351/api/v1/mobile/web?token=$MOBILE_TOKEN"
print "  Mobile API Token：$MOBILE_TOKEN"
print ""

exec "$DIR/重启电脑端辅助.command"
